export const FULLH4RD_BASE_CATEGORY_URL = 'https://fullh4rd.com.ar/cat/supra/';
export const GEZATEK_BASE_CATEGORY_URL = 'https://gezatek.com.ar/';

export const FULLH4RD_CATEGORIES = [
  '54/accesorios/1',
  '12/almacenamiento/1',
  '28/auriculares-y-microfonos/1',
  '52/cables/1',
  '21/camaras/1',
  '27/conectividad-y-redes/1',
  '48/consolas/1',
  '5/equipos/1',
  '25/estabilizadores-y-ups/1',
  '26/fuentes/1',
  '6/gabinetes/1',
  '20/impresoras/1',
  '44/joystick/1',
  '4/memorias/1',
  '1/microprocesador/1',
  '18/monitores/1',
  '2/motherboard/1',
  '56/mouse-pad/1',
  '14/mouses/1',
  '30/multimedia/1',
  '32/notebooks/1',
  '15/parlantes/1',
  '33/pendrives/1',
  '3/placas-de-video/1',
  '37/proyectores/1',
  '23/refrigeracion/1',
  '55/sillas-gamer/1',
  '60/smartwatches/1',
  '34/software/1',
  '8/teclados/1',
  '31/telefonia/1',
] as const;

export const GEZATEK_CATEGORIES = [
  'almacenamiento/',
  'electro/',
  'gabinetes-y-fuentes/',
  'memorias-portatiles/',
  'memorias-ram/',
  'motherboards/',
  'notebooks-y-accesorios/',
  'otros/',
  'perifericos/',
  'placas-de-video/',
  'procesadores/',
  'redes/',
  'refrigeracion/',
] as const;
